db:
    mode: mysql
    db_name: fast_db
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
redis:
    addr: "127.0.0.1:6379"
    password: "123"
    db: 1
system:             # gin配置
    mode: release   # debug or release or test
    ip: 127.0.0.1
    port: 8080